name: Deploy

on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop, master]
  pull_request_target:
    types: [labeled]
    branches: [develop, master]
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    env:
      test_secret: ${{ secrets.TEST_SECRET }}
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push'
      || github.event.pull_request.head.repo.full_name == github.repository
      || contains(github.event.pull_request.labels.*.name, 'safe to test')

    steps:
    - name: Test
      run: |
        echo Hello there! $test_secret
